### 配置 spring boot 重写
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 1
    host: localhost
    port: 6379
###  Eureka Client 端配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
